
services:
  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:v2.2.3
    restart: always
    ports:
       - "8888:8080"
    env_file:
      - .env
    volumes:
      - .evolution_instances:/evolution/instances
      - .evolution_store:/evolution/store

volumes:
  evolution_instances:
