services:
  minio:
   image: minio/minio:latest
   ports:
     - '9000:9000'
     - '9001:9001'
   volumes:
     - './minio_data:/data'
   environment:
     - MINIO_ROOT_USER=syncmate
     - MINIO_ROOT_PASSWORD=sync.mate
     - MINIO_DEFAULT_BUCKETS=syncmate
   command: server /data --console-address ":9001"
   networks:
     - syncmate_hom

networks:
  syncmate_hom:
    external: true
